### ISSUE TITLE
Does not support null safety

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [axel-op/dart_package_analyzer#11]
I think Pub now analyzes using a different channel because they analyze for null safety support, which requires the `beta` channel.

**Comment by axel-op** [comment]
Hello, thanks for notifying me. That's right, null-safety reports have been added to pana, but no points are granted based on it for now. However I think I won't switch the channel for this action, as null-safety support will soon be added to `stable`. Did your workflow break because of this?

Btw you can always use the solution [I suggested here](https://github.com/axel-op/dart-package-analyzer/issues/5) to use the version of Dart and Flutter you want.

**Comment by creativecreatorormaybenot** [comment]
Yeah, it breaks the workflows. However, I suppose it is fine.

**Comment by creativecreatorormaybenot** [comment]
@axel-op The main reason for the issue is that Pub is currently (due to null safety) not running `stable` for that analysis while the action is.

**Comment by axel-op** [comment]
Solved with f4d9bfc3a6e0ffb3c8b8b60730b068a37b7ba29d.
