### ISSUE TITLE
Package fails because of unresolved dependencies

### ISSUE THREAD

**Issue by pph7** [axel-op/dart_package_analyzer#13]
In my current project, dart-package-analyzer always fails on the

`flutter pub upgrade `

command with the following error message:

```
ERR: Because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2 and firebase_auth_web >=0.3.0-dev.1 depends on intl ^0.16.1, flutter_localizations from sdk is incompatible with firebase_auth_web >=0.3.0-dev.1.
 And because firebase_auth >=0.20.0 depends on firebase_auth_web ^0.3.2+6, flutter_localizations from sdk is incompatible with firebase_auth >=0.20.0.
 So, because repeat_native depends on both firebase_auth ^0.20.0 and flutter_localizations any from sdk, version solving failed.
```

See also: https://github.com/flutter/flutter/issues/71801

Locally this command runs without a problem. On idea is that the package analyzer uses the beta channel while we are using the stable channel.

Possible solution: Add a configuration option where we can choose which version of flutter to use.

**Comment by pph7** [comment]
I just confirmed that this problem does not occur in v2 of the package analyzer.

**Comment by axel-op** [comment]
Hi,

Thanks for the issue. As you guessed, this will be automatically resolved once the `firebase_auth_web` will be updated. The reason why I've set the Flutter channel on `beta` is to maintain compatibility with libraries that have opted in null safety (see #11).

> I just confirmed that this problem does not occur in v2 of the package analyzer.

I don't recommend using `v2`, because it uses an old version of Pana that is not updated anymore.

> Possible solution: Add a configuration option where we can choose which version of flutter to use.

See #5 to use a different Flutter channel with this action.

**Comment by axel-op** [comment]
I think that this has been solved with https://github.com/FirebaseExtended/flutterfire/commit/1e8f48a1b2128a7e9ee730423dc647759dfa5bb2#.
